-- 001_create_sessions.sql
-- Creates sessions and session_events tables for live sessions
-- Includes a trigger to bump seq on updates and example RLS policies

-- Sessions table: stores current session state (mutable)
CREATE TABLE IF NOT EXISTS public.sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  owner uuid,
  payload jsonb,
  seq bigint DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Trigger function to update updated_at and increment seq on updates
CREATE OR REPLACE FUNCTION public.sessions_seq_trigger()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  IF TG_OP = 'UPDATE' THEN
    NEW.seq := OLD.seq + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sessions_seq ON public.sessions;
CREATE TRIGGER sessions_seq
BEFORE UPDATE ON public.sessions
FOR EACH ROW
EXECUTE FUNCTION public.sessions_seq_trigger();

-- Optional append-only events table (useful for CRDT/event-sourcing)
CREATE TABLE IF NOT EXISTS public.session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint REFERENCES public.sessions(id) ON DELETE CASCADE,
  actor uuid,
  op jsonb,
  seq bigint,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_session_events_session_seq ON public.session_events(session_id, seq DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_updated_at ON public.sessions(updated_at DESC);

-- Enable Row Level Security (RLS) and example policies.
-- Adjust policies to fit your auth model. These examples assume inserting clients
-- will set `owner = auth.uid()` when creating a session.

-- Enable RLS
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_events ENABLE ROW LEVEL SECURITY;

-- Allow anyone (public) to read sessions and events
CREATE POLICY sessions_public_select ON public.sessions FOR SELECT USING (true);
CREATE POLICY session_events_public_select ON public.session_events FOR SELECT USING (true);

-- Allow authenticated users to create sessions, but require owner to match auth.uid()
CREATE POLICY sessions_auth_insert ON public.sessions FOR INSERT WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = owner);

-- Allow only the owner to update or delete the session
CREATE POLICY sessions_owner_update ON public.sessions FOR UPDATE USING (auth.uid() = owner) WITH CHECK (auth.uid() = owner);
CREATE POLICY sessions_owner_delete ON public.sessions FOR DELETE USING (auth.uid() = owner);

-- Allow authenticated users to insert session_events (presence/ops)
CREATE POLICY session_events_insert_auth ON public.session_events FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- NOTE: Customize these policies to your needs. For example, allow public updates
-- for ephemeral sessions, or use a membership table to grant write access to multiple
-- users.
